version: '3.4'

services:
  backend:
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    ports:
      - 10001:10001
  db:
    restart: "no"
    ports:
      - 4321:5432

  db_isolated:
    restart: "no"
    ports:
      - 3456:5432